name: Docs

on:
  workflow_dispatch:
  release:
    types: [published]
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
       sudo apt update -y
       sudo apt install -y pandoc
       make venv

    - name: Build documentation
      run: |
        make docs

    - name: Publish documentation
      if: ${{ github.ref == 'refs/heads/main' || contains('refs/tags/', github.ref) }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
